Development
rawdaGastan/dmidecode pull request #2
Opened 2022-10-31 13:37 UTC by rawdaGastan

## Issues

- https://github.com/rawdaGastan/dmidecode/issues/1

2022-10-31 13:54 UTC, xmonader requested changes

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +type Entry = map[string][]string
loved how you are using alias declarations

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +func NewDMIDecoder() DMIDecoder {
We could have separated the concerns by passing string as a parameter, and we make it the user problem to get a valid dmidecode result to pass to the function, maybe using another function like `GetDMIDecodeOutput()`

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +	installed  bool
for separation of concertns, the DMIDecoder should only parse data, into an internal map, it shouldn't know about external software installed e.g `sudo, dmidecode`, it should be a concern of another function, or the user provides it

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +	res, _ := dmidecode.Output()
replace `res` with `out`, typically when people read `res` the assume it's the `status code` or the `return code` which is an `int`, also don't ignore the error, if error happens it needs to be handled or propagated to the user e.g in a container and sudo isn't installed

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +		fmt.Println("dmidecode is not installed in your device")
this should be an error to be returned, if for logging let's use `zerolog` or standard go logging

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +func (dmi *DMIDecoder) Decode() {
either have parameter representing dmi output passed to it to make it pure or depend on the parameter passed from `NewDMIDecoder` instead

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +	if !dmi.installed {
installed check shouldn't be a concern of the dmidecode parser

2022-10-31 13:54 UTC, xmonader commented on pkg/dmi.go
> +				if key == "System Power Controls" {
let's make it generic to handle if the line after `Handle line` is starting with spaces, we ignore it and make a new section, I'm not sure if `System Power Controls` will be the only case

2022-11-01 11:58 UTC, rawdaGastan commented
lgtm

2022-11-01 11:58 UTC, merged